D_s = 0.336            #Shell-side inside diameter (m)
d_o = 0.019            #Tube-side outer diameter (m)
d_i = 0.0166           #Tube-side inside diameter (m)
d_l = 0.019749         #Tube whole diameter (m)
p_t = 0.025            #Tube pitch (m)
Tbl = 45               #Tube bundle Layout (degrees)
L_bc = 0.279           #Central Baffle Spacing (m)
L_bi = 0.318           #Inlet Baffle Spacing (m)
L_bo = 0.318           #Outlet baffle spacing (m)
l_c = 0.0867           #Baffle Cut (m) or 25.8%
N_ss = 1               #Number of sealing strip pairs
D_baffle = 0.333054    #Baffle distance (m)
N_t = 102              #Total number of tubes
L = 4.3                #Tube lenght (m)
w_p = 0.019            #Width of bypass lane (m)
n_p = 2                #Number of tube passes
N_rcc = 9              #Number of effective rube rows crossed durring flow
N_p = 2                #Number of pass partitions
D_otl = 0.321          #Diameter of the outer tube limit
d_tb = 0.000794        #Tube-to-baffle hole diametral clearance (m)
d_sb = 0.002946        #Shell-to-baffle diametral clearance (m)
k_w = 111              #Thermal conductivity of tube wall (W/m * K)
m_s = 36.3             #Oil Flow rate (kg/s)
T_si = 65.6            #Oil inlet temperature (degrees C)
R_of = 0.000176        #Oil side fouling factor (m^2*W/K)
X_t = 0.0354           #Tranverse tube pitch (m)
R_if = 0.000088        #Water side fouling factor (m^2*W/K)
p_s = 849              #Fluid density (kg/m^3)
E = 0.1555             #Heat exchanger Effectiveness
m_t = 18.1             #Water flow rate (kg/s)
T_ti = 32.2            #Water inlet temperature (degrees C)
k = 0.140              #Thermal cunductivity for fluid
m_s = 36.3             #Fluid mass flow rate (kg/s)
u_s = 0.0646           #Fluid dynamic viscosity
Laminar_flow = 0       #Boolean to see if the flow is laminar, 1 is Laminar, 0 is Non-Laminar
Nu_s = 125             #Nusselt number
Bundle_layout = 30     #Tube bundle Layout degree
